/**
 * AuditProfilesList — shows saved audit profiles with quick-run and edit actions.
 */

import { memo } from "react"
import {
  Sparkles, Play, Trash2,
  Shield, Bug, Gauge, TestTube, FileX, Package,
} from "lucide-react"
import { cn } from "../../../../../lib/utils"
import { trpc } from "../../../../../lib/trpc"

interface AuditProfilesListProps {
  projectId: string
}

const CATEGORY_ICONS: Record<string, typeof Shield> = {
  security: Shield,
  bug: Bug,
  performance: Gauge,
  "test-gap": TestTube,
  "dead-code": FileX,
  dependency: Package,
}

const SCHEDULE_LABELS: Record<string, string> = {
  manual: "Manual",
  "on-commit": "On Commit",
  daily: "Daily",
}

export const AuditProfilesList = memo(function AuditProfilesList({ projectId }: AuditProfilesListProps) {
  const profilesQuery = trpc.ambient.listAuditProfiles.useQuery(
    { projectId },
    { placeholderData: (prev) => prev },
  )
  const deleteMutation = trpc.ambient.deleteAuditProfile.useMutation()
  const utils = trpc.useUtils()

  const profiles = profilesQuery.data ?? []

  if (profiles.length === 0) {
    return (
      <div className="py-6 text-center">
        <p className="text-xs text-zinc-600">
          No audit profiles. Audit a zone to auto-generate one, or create a custom profile.
        </p>
      </div>
    )
  }

  return (
    <div className="pt-3 space-y-2">
      {profiles.map((profile: any) => (
        <div
          key={profile.id}
          className="flex items-start gap-3 px-3 py-2.5 rounded-lg border border-zinc-800/40 bg-zinc-900/20"
        >
          <div className="flex-1 min-w-0 space-y-1.5">
            {/* Name + badges */}
            <div className="flex items-center gap-2">
              <span className="text-[11px] font-medium text-zinc-200 truncate">
                {profile.name}
              </span>
              {profile.isAutoGenerated && (
                <span className="flex items-center gap-0.5 text-[8px] font-mono px-1.5 py-0.5 rounded bg-purple-500/15 text-purple-400">
                  <Sparkles className="w-2 h-2" />AI
                </span>
              )}
              <span className="text-[8px] font-mono px-1.5 py-0.5 rounded bg-zinc-800 text-zinc-500">
                {SCHEDULE_LABELS[profile.schedule] || profile.schedule}
              </span>
            </div>

            {/* Description */}
            {profile.description && (
              <p className="text-[9px] text-zinc-600 line-clamp-1">{profile.description}</p>
            )}

            {/* Categories + zones */}
            <div className="flex items-center gap-2 flex-wrap">
              {profile.categories?.map((cat: string) => {
                const CatIcon = CATEGORY_ICONS[cat] || Shield
                return (
                  <span key={cat} className="flex items-center gap-0.5 text-[8px] font-mono text-zinc-500">
                    <CatIcon className="w-2.5 h-2.5" />{cat}
                  </span>
                )
              })}
            </div>

            {profile.zoneNames?.length > 0 && (
              <div className="flex items-center gap-1 flex-wrap">
                {profile.zoneNames.map((name: string) => (
                  <span key={name} className="text-[8px] font-mono px-1 py-0.5 rounded bg-zinc-800/50 text-zinc-500">
                    {name}
                  </span>
                ))}
              </div>
            )}
          </div>

          {/* Actions */}
          <div className="flex items-center gap-1 shrink-0">
            <button
              onClick={() => {
                deleteMutation.mutate({ profileId: profile.id }, {
                  onSuccess: () => utils.ambient.listAuditProfiles.invalidate({ projectId }),
                })
              }}
              className="p-1 rounded text-zinc-600 hover:text-red-400 hover:bg-red-500/10 transition-colors"
              title="Delete profile"
            >
              <Trash2 className="w-3 h-3" />
            </button>
          </div>
        </div>
      ))}
    </div>
  )
})
