/**
 * Shared types for the System Map Audit system.
 * Used by both main process (engine, tRPC) and renderer (dashboard, zone cards).
 */

// ============ ENUMS ============

export type AuditTrigger = "manual-zone" | "manual-all" | "on-commit" | "scheduled" | "skill"
export type AuditRunStatus = "running" | "completed" | "failed" | "cancelled"
export type FindingStatus = "open" | "resolved" | "dismissed" | "wont-fix"
export type AuditSchedule = "manual" | "on-commit" | "daily"

// ============ AUDIT RUNS ============

export interface AuditRunSummary {
  id: string
  projectId: string
  profileId: string | null
  trigger: AuditTrigger
  status: AuditRunStatus
  totalFindings: number
  errorCount: number
  warningCount: number
  infoCount: number
  overallScore: number
  durationMs: number
  initiatedBy: string
  partialErrors: Array<{ zoneId: string; error: string }>
  startedAt: string
  completedAt: string | null
  createdAt: string
  zones: Array<{ zoneId: string; zoneName: string; zoneScore: number }>
}

// ============ AUDIT FINDINGS ============

export interface AuditFindingRow {
  id: string
  runId: string
  projectId: string
  zoneId: string
  zoneName: string
  category: string
  severity: string
  title: string
  description: string
  confidence: number
  affectedFiles: string[]
  suggestedPrompt: string
  status: FindingStatus
  dismissReason: string | null
  resolvedSubChatId: string | null
  orchestrationTaskId: string | null
  resolvedAt: string | null
  createdAt: string
}

// ============ AUDIT PROFILES ============

export interface AuditProfileRow {
  id: string
  projectId: string
  name: string
  description: string
  zoneIds: string[] | null
  zoneNames: string[] | null
  categories: string[]
  severityThreshold: string
  customPromptAppend: string
  schedule: AuditSchedule
  isAutoGenerated: boolean
  nextScheduledAt: string | null
  lastUsedAt: string | null
  createdAt: string
  updatedAt: string
}

// ============ PROGRESS & TRENDS ============

export interface AuditProgress {
  zoneId: string
  zoneName: string
  status: "pending" | "profiling" | "auditing" | "done" | "error"
  findings: number
  errorMessage?: string
}

export interface ZoneTrend {
  zoneId: string
  zoneName: string
  currentScore: number
  scores: number[] // last N scores, oldest first
  trend: "up" | "down" | "stable"
}

// ============ ENGINE RESULTS ============

export interface AuditRunResult {
  runId: string
  zonesAudited: number
  totalFindings: number
  suggestionsCreated: number
  overallScore: number
  durationMs: number
  progress: AuditProgress[]
  partialErrors: Array<{ zoneId: string; error: string }>
}
